# Generated by Django 5.0.7 on 2024-07-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='timing',
            field=models.DateField(),
        ),
    ]
